version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgresql:admin@db:5432/crud-cus-prod-db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud-cus-prod-db
    ports:
      - '5432:5432'
